{% set name = "opencadd" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/volkamerlab/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 5f256425dc42f377a24cde17461723964d8791f8dd10735d34471a85bebbebc6

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - matplotlib-base
    - mdanalysis
    - nglview
    - jsonschema <4.0.0
    - bravado
    - biopandas
    - rdkit
    - tqdm
    - biotite
    - biopython <=1.77
    # Not available under Windows yet
    #- mmligner
    #- theseus

test:
  requires:
    - python {{ python_min }}
  imports:
    - opencadd

about:
  home: https://github.com/volkamerlab/opencadd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python library for structural cheminformatics
  description: |
    A Python library for structural cheminformatics
  doc_url: https://opencadd.readthedocs.io/en/latest
  dev_url: https://github.com/volkamerlab/opencadd

extra:
  recipe-maintainers:
    - dominiquesydow
    - jaimergp
